# Generated by Django 5.2.14 on 2026-06-03 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_opportunity_opportunityapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
