# Generated by Django 5.2.14 on 2026-06-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_opportunity_saved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
    ]
