# Generated by Django 5.2.6 on 2025-10-01 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_players',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('scout', 'Scout'), ('club', 'Club'), ('fan', 'Fan')], max_length=20),
        ),
    ]
