# Generated by Django 5.2.14 on 2026-06-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_saved_players_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_density', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=20)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_contact', models.BooleanField(default=True)),
                ('notify_reports', models.BooleanField(default=True)),
                ('notify_social', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged-in users'), ('scouts_clubs', 'Scouts and clubs')], default='public', max_length=20)),
                ('show_email', models.BooleanField(default=False)),
                ('allow_contact', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('default_feed', models.CharField(choices=[('all', 'All football posts'), ('following', 'Following only'), ('talent', 'Talent spots')], default='all', max_length=20)),
                ('autoplay_video', models.BooleanField(default=False)),
                ('show_media', models.BooleanField(default=True)),
                ('compact_cards', models.BooleanField(default=False)),
                ('player_available', models.BooleanField(default=True)),
                ('player_trials', models.BooleanField(default=False)),
                ('scout_regional_alerts', models.BooleanField(default=True)),
                ('scout_shortlist_alerts', models.BooleanField(default=True)),
                ('club_trial_ready', models.BooleanField(default=True)),
                ('club_contact_alerts', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
