from django.urls import path
from . import views

urlpatterns = [
    path("", views.feed, name="feed"),
    path("talent-spots/", views.talent_spots, name="talent_spots"),
    path("talent-spots/new/", views.create_talent_spot, name="create_talent_spot"),
    path("talent-spots/<int:spot_id>/", views.talent_spot_detail, name="talent_spot_detail"),
    path("talent-spots/<int:spot_id>/report-content/", views.report_talent_spot, name="report_talent_spot"),
    path("talent-spots/<int:spot_id>/confirm/", views.confirm_talent_spot, name="confirm_talent_spot"),
    path("talent-spots/<int:spot_id>/verify/", views.verify_talent_spot, name="verify_talent_spot"),
    path("talent-spots/<int:spot_id>/report/", views.create_scout_report, name="create_scout_report"),
    path("talent-spots/<int:spot_id>/shortlist/", views.add_to_shortlist, name="add_to_shortlist"),
    path("talent-spots/<int:spot_id>/claim/", views.claim_talent_spot, name="claim_talent_spot"),
    path("talent-spot-claims/<int:claim_id>/<str:action>/", views.review_talent_spot_claim, name="review_talent_spot_claim"),
    path("club-shortlist/", views.club_shortlist, name="club_shortlist"),
    path("club-shortlist/<int:entry_id>/update/", views.update_shortlist_entry, name="update_shortlist_entry"),
    path("talent-spots/<int:spot_id>/contact/", views.create_contact_request, name="create_contact_request"),
    path("contact-requests/", views.contact_requests, name="contact_requests"),
    path("contact-requests/<int:request_id>/cancel/", views.cancel_contact_request, name="cancel_contact_request"),
    path("contact-requests/<int:request_id>/<str:action>/", views.respond_contact_request, name="respond_contact_request"),
    path("opportunities/", views.opportunities, name="opportunities"),
    path("opportunities/new/", views.create_opportunity, name="create_opportunity"),
    path("opportunities/applications/", views.my_opportunity_applications, name="my_opportunity_applications"),
    path("opportunities/manage/", views.manage_opportunities, name="manage_opportunities"),
    path("opportunities/saved/", views.saved_opportunities, name="saved_opportunities"),
    path("opportunities/<int:opportunity_id>/edit/", views.edit_opportunity, name="edit_opportunity"),
    path("opportunities/<int:opportunity_id>/toggle-active/", views.toggle_opportunity_active, name="toggle_opportunity_active"),
    path("opportunities/<int:opportunity_id>/", views.opportunity_detail, name="opportunity_detail"),
    path("opportunities/<int:opportunity_id>/apply/", views.apply_opportunity, name="apply_opportunity"),
    path("opportunities/<int:opportunity_id>/save/", views.toggle_save_opportunity, name="toggle_save_opportunity"),
    path("opportunity-applications/<int:application_id>/withdraw/", views.withdraw_opportunity_application, name="withdraw_opportunity_application"),
    path("opportunity-applications/<int:application_id>/<str:action>/", views.update_opportunity_application, name="update_opportunity_application"),
    path("notifications/", views.notifications, name="notifications"),
    path("notifications/<int:notification_id>/open/", views.open_notification, name="open_notification"),
    path("notifications/<int:notification_id>/read/", views.mark_notification_read, name="mark_notification_read"),
    path("notifications/read/", views.mark_notifications_read, name="mark_notifications_read"),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('report-post/<int:post_id>/', views.report_post, name='report_post'),
    path('comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path("repost/<int:post_id>/", views.repost_post, name="repost_post"),
    path('fetch-new-posts/', views.fetch_new_posts, name='fetch_new_posts'),
    path("moderation/", views.moderation_queue, name="moderation_queue"),
    path("moderation/<int:report_id>/<str:action>/", views.review_content_report, name="review_content_report"),

]
