# Generated by Django 5.2.6 on 2025-10-01 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('preferred_foot', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], default='right', max_length=10)),
                ('position', models.CharField(help_text='E.g., Striker, Midfielder, Defender, Goalkeeper', max_length=50)),
                ('current_club', models.CharField(blank=True, max_length=100, null=True)),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='players/profile_pics/')),
                ('highlight_video', models.URLField(blank=True, help_text='YouTube/Vimeo link to highlights', null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
