# Generated by Django 5.2.6 on 2025-10-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='region',
            field=models.CharField(blank=True, help_text='Region/Province', max_length=100, null=True),
        ),
    ]
