# Generated by Django 5.2.6 on 2025-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='position',
            field=models.CharField(choices=[('Forward', 'Forward'), ('Midfielder', 'Midfielder'), ('Defender', 'Defender'), ('Goalkeeper', 'Goalkeeper')], help_text='E.g., Striker, Midfielder, Defender, Goalkeeper', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu')], help_text='Region/Province', max_length=100, null=True),
        ),
    ]
